// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{
    using Newtonsoft.Json;

    // database_firewall_rules
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class database_firewall_rule
    {
        [Column(@"id", Order = 1, TypeName = "int")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int id { get; set; } // id (Primary key)

        [Column(@"name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Name")]
        public string name { get; set; } // name (Primary key) (length: 128)

        [Column(@"start_ip_address", Order = 3, TypeName = "varchar")]
        [Required]
        [MaxLength(45)]
        [StringLength(45)]
        [Key]
        [Display(Name = "Start ip address")]
        public string start_ip_address { get; set; } // start_ip_address (Primary key) (length: 45)

        [Column(@"end_ip_address", Order = 4, TypeName = "varchar")]
        [Required]
        [MaxLength(45)]
        [StringLength(45)]
        [Key]
        [Display(Name = "End ip address")]
        public string end_ip_address { get; set; } // end_ip_address (Primary key) (length: 45)

        [Column(@"create_date", Order = 5, TypeName = "datetime")]
        [Required]
        [Key]
        [Display(Name = "Create date")]
        public System.DateTime create_date { get; set; } // create_date (Primary key)

        [Column(@"modify_date", Order = 6, TypeName = "datetime")]
        [Required]
        [Key]
        [Display(Name = "Modify date")]
        public System.DateTime modify_date { get; set; } // modify_date (Primary key)
    }

}
// </auto-generated>
