// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{
    using Newtonsoft.Json;

    // Examiners
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Examiner
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "First name")]
        public string FirstName { get; set; } // FirstName (length: 100)

        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Last name")]
        public string LastName { get; set; } // LastName (length: 100)

        // Reverse navigation

        /// <summary>
        /// Child Questions where [Questions].[LastEditedBy] point to this entity (FKQuestions_Examiners)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<Question> LastEditedBy { get; set; } = new System.Collections.Generic.List<Question>(); // Questions.FKQuestions_Examiners
        /// <summary>
        /// Child Questions where [Questions].[LastEditedBy] point to this entity (FK_Questions_Examiners)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<Question> Questions_LastEditedBy { get; set; } = new System.Collections.Generic.List<Question>(); // Questions.FK_Questions_Examiners
        /// <summary>
        /// Child Tests where [Tests].[LastEditedBy] point to this entity (FKTests_Examiners)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<Test> Tests { get; set; } = new System.Collections.Generic.List<Test>(); // Tests.FKTests_Examiners
        /// <summary>
        /// Child TestResults where [TestResults].[HandsOnExaminer] point to this entity (FKTestResults_Examiners_HandsOn)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<TestResult> HandsOnExaminer { get; set; } = new System.Collections.Generic.List<TestResult>(); // TestResults.FKTestResults_Examiners_HandsOn
        /// <summary>
        /// Child TestResults where [TestResults].[ScoringExaminer] point to this entity (FKTestResults_Examiners_Scoring)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<TestResult> ScoringExaminer { get; set; } = new System.Collections.Generic.List<TestResult>(); // TestResults.FKTestResults_Examiners_Scoring
    }

}
// </auto-generated>
