// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{

    // OtherRestrictions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class OtherRestriction
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Test result")]
        public System.Guid TestResult { get; set; } // TestResult

        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Additional info")]
        public string AdditionalInfo { get; set; } // AdditionalInfo (length: 200)

        // Foreign keys

        /// <summary>
        /// Parent TestResult pointed by [OtherRestrictions].([TestResult]) (FKOtherRestrictions_TestResult)
        /// </summary>
        public virtual TestResult TestResult_TestResult { get; set; } // FKOtherRestrictions_TestResult
    }

}
// </auto-generated>
