// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{
    using Newtonsoft.Json;

    // Sections
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Section
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Test")]
        public System.Guid Test { get; set; } // Test

        [Required]
        [Display(Name = "Section number")]
        public int SectionNumber { get; set; } // SectionNumber

        [Required]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Title")]
        public string Title { get; set; } // Title (length: 1000)

        [Required]
        [MaxLength(1000)]
        [StringLength(1000)]
        [Display(Name = "Description")]
        public string Description { get; set; } // Description (length: 1000)

        [Display(Name = "Last edited by")]
        public System.Guid? LastEditedBy { get; set; } // LastEditedBy

        [Required]
        [Display(Name = "Last edited date")]
        public System.DateTime LastEditedDate { get; set; } = System.DateTime.Now; // LastEditedDate

        // Reverse navigation

        /// <summary>
        /// Child Questions where [Questions].[Section] point to this entity (FKQuestions_Sections)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<Question> Questions { get; set; } = new System.Collections.Generic.List<Question>(); // Questions.FKQuestions_Sections
        /// <summary>
        /// Child TestResultsSections where [TestResultsSections].[Section] point to this entity (FKTestResultsSections_Sections)
        /// </summary>
        [JsonIgnore]
        public System.Collections.Generic.List<TestResultsSection> TestResultsSections { get; set; } = new System.Collections.Generic.List<TestResultsSection>(); // TestResultsSections.FKTestResultsSections_Sections

        // Foreign keys

        /// <summary>
        /// Parent Test pointed by [Sections].([Test]) (FKSections_Tests)
        /// </summary>
        [JsonIgnore]
        public Test Test_Test { get; set; } // FKSections_Tests
    }

}
// </auto-generated>
