// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{

    // Tests
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class Test
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [MaxLength(30)]
        [StringLength(30)]
        [Display(Name = "Short name")]
        public string ShortName { get; set; } // ShortName (length: 30)

        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 500)

        [Required]
        [Display(Name = "Last edited by")]
        public System.Guid LastEditedBy { get; set; } // LastEditedBy

        [Required]
        [Display(Name = "Last edited date")]
        public System.DateTime LastEditedDate { get; set; } = System.DateTime.Now; // LastEditedDate

        // Reverse navigation

        /// <summary>
        /// Child Questions where [Questions].[Test] point to this entity (FK_Questions_Tests)
        /// </summary>
        public virtual System.Collections.Generic.List<Question> Questions_Test { get; set; } = new System.Collections.Generic.List<Question>(); // Questions.FK_Questions_Tests
        /// <summary>
        /// Child Questions where [Questions].[Test] point to this entity (FKQuestions_Tests)
        /// </summary>
        public virtual System.Collections.Generic.List<Question> Questions1 { get; set; } = new System.Collections.Generic.List<Question>(); // Questions.FKQuestions_Tests

        // Foreign keys

        /// <summary>
        /// Parent Examiner pointed by [Tests].([LastEditedBy]) (FKTests_Examiners)
        /// </summary>
        public virtual Examiner Examiner_LastEditedBy { get; set; } // FKTests_Examiners

        /// <summary>
        /// Parent Examiner pointed by [Tests].([LastEditedBy]) (FK_Tests_Examiners)
        /// </summary>
        public virtual Examiner Examiner1 { get; set; } // FK_Tests_Examiners
    }

}
// </auto-generated>
