// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal.Data.Entities
{
    using Newtonsoft.Json;

    // TestResultsAnswers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class TestResultsAnswer
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Test result")]
        public System.Guid TestResult { get; set; } // TestResult

        [Required]
        [Display(Name = "Question")]
        public System.Guid Question { get; set; } // Question

        [Required]
        [MaxLength(2)]
        [StringLength(2)]
        [Display(Name = "Answer")]
        public string Answer { get; set; } // Answer (length: 2)

        [Required]
        [Display(Name = "Yes no")]
        public bool YesNo { get; set; } = false; // YesNo

        // Foreign keys

        /// <summary>
        /// Parent Question pointed by [TestResultsAnswers].([Question]) (FKTestResultsAnswers_Questions)
        /// </summary>
        [JsonIgnore]
        public Question Question_Question { get; set; } // FKTestResultsAnswers_Questions
    }

}
// </auto-generated>
