//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCanine.AdminPortal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultsAnswer
    {
        public System.Guid Id { get; set; }
        public System.Guid TestResult { get; set; }
        public System.Guid Question { get; set; }
        public string Answer { get; set; }
        public bool YesNo { get; set; }
    
        public virtual Question Question1 { get; set; }
        public virtual TestResult TestResult1 { get; set; }
    }
}
