CREATE TABLE [dbo].[Sections]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Test] UNIQUEIDENTIFIER NOT NULL,
	[SectionNumber] INT NOT NULL,
	[Title] VARCHAR(1000) NOT NULL,
	[Description] VARCHAR(1000) NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NULL,
	[LastEditedDate] DATETIME NOT NULL DEFAULT GetDate()
)
