CREATE TABLE [dbo].[Tests]
(
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[ShortName] VARCHAR(30) NOT NULL,
	[Name] VARCHAR(500) NOT NULL,
	[LastEditedBy] VARCHAR(255) NOT NULL,
	[LastEditedDate] DATETIME NOT NULL DEFAULT GetDate()
)
