CREATE TABLE [dbo].[TestResultsSections]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT (NEWID()),
	[TestResult] UNIQUEIDENTIFIER NOT NULL,
	[Section] UNIQUEIDENTIFIER NOT NULL,
	[Notes] VARCHAR(5000) NULL
)
