CREATE TABLE [dbo].[Tests]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[ShortName] VARCHAR(30) NOT NULL,
	[Name] VARCHAR(500) NOT NULL,
	[TestVersion_DateTime] DATETIME NOT NULL,
	[LastEditedBy] UNIQUEIDENTIFIER NOT NULL,
	[LastEditedDate] DATETIME NOT NULL DEFAULT GetDate()
)
