CREATE TABLE [dbo].[TestResults]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Handler] UNIQUEIDENTIFIER NOT NULL,
	[Dog] UNIQUEIDENTIFIER NOT NULL,
	[PassedTest] BIT NULL,
	[TestDate] DATETIME NOT NULL,
	[ScoringExaminer] UNIQUEIDENTIFIER NOT NULL,
	[HandsOnExaminer] UNIQUEIDENTIFIER NOT NULL,
	[CertificationType] UNIQUEIDENTIFIER NULL,
	[EquipmentRestrictions] UNIQUEIDENTIFIER NULL,
	[ScoringExaminerSignature] VARBINARY(MAX) NULL,
	[HandsOnSignature] VARBINARY(MAX) NULL,
	[HandlerSignature] VARBINARY(MAX) NULL
)
