//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCanine.AdminPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestResult()
        {
            this.TestResultsAnswers = new HashSet<TestResultsAnswer>();
            this.TestResultsSections = new HashSet<TestResultsSection>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Test { get; set; }
        public System.Guid Handler { get; set; }
        public System.Guid Dog { get; set; }
        public Nullable<bool> PassedTest { get; set; }
        public string ReasonForFailure { get; set; }
        public string Notes { get; set; }
        public bool PassedConnectingCanines { get; set; }
        public Nullable<bool> ShadowVisitRequirement { get; set; }
        public bool EligibleToRetest { get; set; }
        public System.DateTime TestDate { get; set; }
        public System.Guid ScoringExaminer { get; set; }
        public System.Guid HandsOnExaminer { get; set; }
        public Nullable<System.Guid> CertificationType { get; set; }
        public Nullable<System.Guid> EquipmentRestrictions { get; set; }
        public string OtherRestrictions { get; set; }
        public bool PracticeLabRequirement { get; set; }
        public byte[] ScoringExaminerSignature { get; set; }
        public byte[] HandsOnSignature { get; set; }
        public byte[] HandlerSignature { get; set; }
    
        public virtual CertificationType CertificationType1 { get; set; }
        public virtual Dog Dog1 { get; set; }
        public virtual EquipmentRestriction EquipmentRestriction { get; set; }
        public virtual Examiner Examiner { get; set; }
        public virtual Examiner Examiner1 { get; set; }
        public virtual Handler Handler1 { get; set; }
        public virtual Test Test1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultsAnswer> TestResultsAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestResultsSection> TestResultsSections { get; set; }
    }
}
