// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProjectCanine.AdminPortal.Data.EfCfgs
{
    using ProjectCanine.AdminPortal.Data;
    using ProjectCanine.AdminPortal.Data.Entities;

    // database_firewall_rules
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class database_firewall_ruleEfConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<database_firewall_rule>
    {
        public database_firewall_ruleEfConfig()
            : this("sys")
        {
        }

        public database_firewall_ruleEfConfig(string schema)
        {
            Property(x => x.start_ip_address).IsUnicode(false);
            Property(x => x.end_ip_address).IsUnicode(false);
        }
    }

}
// </auto-generated>
