// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProjectCanine.AdminPortal.Data.EfCfgs
{
    using ProjectCanine.AdminPortal.Data;
    using ProjectCanine.AdminPortal.Data.Entities;

    // Questions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class QuestionEfConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Question>
    {
        public QuestionEfConfig()
            : this("dbo")
        {
        }

        public QuestionEfConfig(string schema)
        {
            Property(x => x.Text).IsUnicode(false);
            Property(x => x.LastEditedBy).IsOptional();

        }
    }

}
// </auto-generated>
