// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProjectCanine.AdminPortal_OLD.Data.EfCfgs
{
    using ProjectCanine.AdminPortal_OLD.Data;
    using ProjectCanine.AdminPortal_OLD.Data.Entities;

    // Examiners
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class ExaminerEfConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Examiner>
    {
        public ExaminerEfConfig()
            : this("dbo")
        {
        }

        public ExaminerEfConfig(string schema)
        {
            Property(x => x.FirstName).IsUnicode(false);
            Property(x => x.LastName).IsUnicode(false);
        }
    }

}
// </auto-generated>
