// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProjectCanine.AdminPortal_OLD.Data.EfCfgs
{
    using ProjectCanine.AdminPortal_OLD.Data;
    using ProjectCanine.AdminPortal_OLD.Data.Entities;

    // Sections
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class SectionEfConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Section>
    {
        public SectionEfConfig()
            : this("dbo")
        {
        }

        public SectionEfConfig(string schema)
        {
            Property(x => x.Title).IsUnicode(false);
            Property(x => x.Description).IsUnicode(false);
            Property(x => x.LastEditedBy).IsOptional();

        }
    }

}
// </auto-generated>
