// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace ProjectCanine.AdminPortal_OLD.Data.EfCfgs
{
    using ProjectCanine.AdminPortal_OLD.Data;
    using ProjectCanine.AdminPortal_OLD.Data.Entities;

    // TestResultsAnswers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class TestResultsAnswerEfConfig : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<TestResultsAnswer>
    {
        public TestResultsAnswerEfConfig()
            : this("dbo")
        {
        }

        public TestResultsAnswerEfConfig(string schema)
        {
            Property(x => x.Answer).IsUnicode(false);

        }
    }

}
// </auto-generated>
