// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectCanine.AdminPortal_OLD.Data.Entities
{
    using Newtonsoft.Json;

    // TestResultsSections
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class TestResultsSection
    {
        [Column(@"Id", Order = 1, TypeName = "uniqueidentifier")]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public System.Guid Id { get; set; } // Id (Primary key)

        [Required]
        [Display(Name = "Test result")]
        public System.Guid TestResult { get; set; } // TestResult

        [Required]
        [Display(Name = "Section")]
        public System.Guid Section { get; set; } // Section

        [MaxLength(5000)]
        [StringLength(5000)]
        [Display(Name = "Notes")]
        public string Notes { get; set; } // Notes (length: 5000)

        // Foreign keys

        /// <summary>
        /// Parent Section pointed by [TestResultsSections].([Section]) (FKTestResultsSections_Sections)
        /// </summary>
        [JsonIgnore]
        public Section Section_Section { get; set; } // FKTestResultsSections_Sections
    }

}
// </auto-generated>
